[versions]
fleet-sdk = "0.6.237"
rpc-compiler = "2.0.0-0.2"
fleet-runtime = "1.45.162"
fleet-runtime-min-version = "1.45.0"
fleet-runtime-max-version = "1.8191.999"

intellij-sdk = "2.1.0"
intellij-instrumenting-compiler = "241.18034.82"
intellij-runtime = "251-SNAPSHOT"
intellij-runtime-min-version = "251.0"
intellij-runtime-max-version = "251.*"

kotlin = "2.0.0"
kotlinx-serialization = "1.6.3"

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-serialization-json-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json-jvm", version.ref = "kotlinx-serialization" }

[plugins]
fleet-plugin = { id = "org.jetbrains.fleet-plugin", version.ref = "fleet-sdk" }
fleet-plugin-layer = { id = "org.jetbrains.fleet-plugin-layer", version.ref = "fleet-sdk" }
rpc-compiler = { id = "rpc", version.ref = "rpc-compiler" }
intellij-plugin = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-sdk" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
